CREATE TABLE ORDERS
(
    ID                  NUMBER    NOT NULL,
    CONSTRAINT PK_ORDERS PRIMARY KEY (ID),
    USER_ID             NUMBER    NOT NULL,
    CONSTRAINT FK_USERS_ORDERS FOREIGN KEY (USER_ID) REFERENCES HOTELS (ID),
    ROOM_ID             NUMBER    NOT NULL,
    CONSTRAINT FK_ROOMS_ORDERS FOREIGN KEY (ROOM_ID) REFERENCES ROOMS (ID),
    DATE_AVAILABLE_FROM TIMESTAMP NOT NULL,
    DATE_AVAILABLE_TO   TIMESTAMP NOT NULL,
    MONEY_PAID          NUMBER    NOT NULL
);