CREATE TABLE USERS
(
    ID        NUMBER NOT NULL,
    CONSTRAINT PK_USERS PRIMARY KEY (ID),
    NAME      NVARCHAR2(50) NOT NULL,
    PASSWORD  NVARCHAR2(50) NOT NULL,
    COUNTRY   NVARCHAR2(30) NOT NULL,
    -- represents enum
    USER_TYPE NUMBER NOT NULL
);