CREATE TABLE HOTELS
(
    ID      NUMBER NOT NULL,
    CONSTRAINT PK_HOTELS PRIMARY KEY (ID),
    NAME    NVARCHAR2(50) NOT NULL,
    COUNTRY NVARCHAR2(30) NOT NULL,
    STREET  NVARCHAR2(30) NOT NULL
);